# Generated by Django 3.2.5 on 2021-08-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
